version: 2

sources:
  - name: sap
    description: Adventure Works sap tables.
    database: cert_lh_24
    schema: sap_adw
    tables:
      
      - name: salesperson
        description: Table with information about the seller who made the sale.
        columns:
          - name: businessentityid
            description: Primary key of the salesperson table.
            tests:
              - unique
              - not_null
      
      - name: businessentity
        description: Table that holds general information about entities, which can be individuals or organizations, involved in various business transactions.
        columns:
          - name: businessentityid
            description: Primary key of the business entity table. Serves as a unique identifier for each entity, whether it is an individual or organization.
            tests:
              - unique
              - not_null

      - name: person
        description: Table containing personal information about individuals, including their name, contact details, and demographic data.
        columns:
          - name: businessentityid
            description: Primary key of the person table. This is a unique identifier linking each person to the corresponding entity in the business entity table.
            tests:
              - unique
              - not_null

      - name: employee
        description: Contains information about employees, including identification details and personal data.
        columns:
          - name: businessentityid
            description: Unique identifier for the employee within the company.
            tests:
              - unique
              - not_null

      - name: address
        description: Stores information about addresses related to employees and customers.
        columns:
          - name: addressid
            description: Unique identifier for the address.
            tests:
              - unique
              - not_null

      - name: stateprovince
        description: Contains information about states and provinces where the company operates.
        columns:
          - name: stateprovinceid
            description: Unique identifier for the state or province.
            tests:
              - unique
              - not_null

      - name: countryregion
        description: Stores data about countries and regions for international operations support.
        columns:
          - name: countryregioncode
            description: Unique code for the country or region.
            tests:
              - unique
              - not_null

      - name: store
        description: Contains information about physical stores, including location and identification details.
        columns:
          - name: businessentityid
            description: Unique identifier for the store within the company.
            tests:
              - unique
              - not_null

      - name: customer
        description: Stores customer data, including identification and contact information.
        columns:
          - name: customerid
            description: Unique identifier for the customer.
            tests:
              - unique
              - not_null

      - name: salesterritory
        description: Contains information about sales territories used to track sales performance in different areas.
        columns:
          - name: territoryid
            description: Unique identifier for the sales territory.
            tests:
              - unique
              - not_null

      - name: personcreditcard
        description: Stores information about credit cards associated with individuals.
        columns:
          - name: businessentityid
            description: Unique identifier for the individual associated with the credit card.
            tests:
              - unique
              - not_null

      - name: creditcard
        description: Contains details about credit cards used in transactions.
        columns:
          - name: creditcardid
            description: Unique identifier for the credit card.
            tests:
              - unique
              - not_null

      - name: salesorderheader
        description: Stores the header information for sales orders, including general order details.
        columns:
          - name: salesorderid
            description: Unique identifier for the sales order.
            tests:
              - unique
              - not_null

      - name: salesorderheadersalesreason
        description: Links sales orders with sales reasons, explaining why the sales order was placed.

      - name: salesreason
        description: Contains the reasons for sales orders, used to categorize and analyze sales.
        columns:
          - name: salesreasonid
            description: Unique identifier for the sales reason.
            tests:
              - unique
              - not_null

      - name: salesorderdetail
        description: Stores detailed line items for each sales order, including product and quantity information.
        columns:
          - name: salesorderdetailid
            description: Unique identifier for the sales order detail record.
            tests:
              - unique
              - not_null

      - name: product
        description: Contains information about products available for sale.
        columns:
          - name: productid
            description: Unique identifier for the product.
            tests:
              - unique
              - not_null

      - name: productsubcategory
        description: Stores information about product subcategories for organizing products.
        columns:
          - name: productsubcategoryid
            description: Unique identifier for the product subcategory.
            tests:
              - unique
              - not_null

      - name: productcategory
        description: Contains information about product categories used to classify products.
        columns:
          - name: productcategoryid
            description: Unique identifier for the product category.
            tests:
              - unique
              - not_null
          
      - name: phonenumbertype
        description: Defines types of phone numbers, such as mobile or home phone.
        columns:
          - name: phonenumbertypeid
            description: Unique identifier for the phone number type.
            tests:
              - unique
              - not_null

      - name: emailaddress
        description: Stores email addresses associated with individuals or entities.
        columns:
          - name: emailaddressid
            description: Unique identifier for the email address.
            tests:
              - unique
              - not_null

      - name: personphone
        description: Links individuals to their phone numbers.
        columns:
          - name: businessentityid
            description: Unique identifier for the individual associated with the phone number.
            tests:
              - unique
              - not_null
